# Default configuration settings
DEFAULT_INTERVAL_SECONDS = 5

# Default thresholds (percentages)
DEFAULT_CPU_WARNING_THRESHOLD = 80.0
DEFAULT_MEM_WARNING_THRESHOLD = 80.0
DEFAULT_DISK_WARNING_THRESHOLD = 85.0
